const LOCALES = {
  COMMON: {
    LBL_WELCOME: 'COMMON:LBL_WELCOME',
    LBL_OK: 'COMMON:LBL_OK',
    LBL_CANCEL: 'COMMON:LBL_CANCEL',
    LBL_LOADING: 'COMMON:LBL_LOADING',
  },
};

export {LOCALES};
