const LOCALES = {
  COMMON: {
    LBL_WELCOME: 'COMMON:LBL_WELCOME',
    LBL_OK: 'COMMON:LBL_OK',
    LBL_CANCEL: 'COMMON:LBL_CANCEL',
    LBL_LOADING: 'COMMON:LBL_LOADING',
  },
  BOTTOM_TAB: {
    LBL_HOME: 'BOTTOM_TAB:LBL_HOME',
    LBL_EXPERIMENT: 'BOTTOM_TAB:LBL_EXPERIMENT',
    LBL_RECORD: 'BOTTOM_TAB:LBL_RECORD',
    LBL_NOTIFICATION: 'BOTTOM_TAB:LBL_NOTIFICATION',
  },
};

export {LOCALES};
