const LOCALES = {
  COMMON: {
    LBL_WELCOME: 'COMMON:LBL_WELCOME',
    LBL_OK: 'COMMON:LBL_OK',
    LBL_CANCEL: 'COMMON:LBL_CANCEL',
    LBL_LOADING: 'COMMON:LBL_LOADING',
  },
  BOTTOM_TAB: {
    LBL_HOME: 'BOTTOM_TAB:LBL_HOME',
    LBL_EXPERIMENT: 'BOTTOM_TAB:LBL_EXPERIMENT',
    LBL_RECORD: 'BOTTOM_TAB:LBL_RECORD',
    LBL_NOTIFICATION: 'BOTTOM_TAB:LBL_NOTIFICATION',
  },
  EXPERIMENT: {
    LBL_EXPERIMENT: 'EXPERIMENT:LBL_EXPERIMENT',
    LBL_SEARCH_EXPERIMENT: 'EXPERIMENT:LBL_SEARCH_EXPERIMENT',
    LBL_CROP: 'EXPERIMENT:LBL_CROP',
    LBL_PROJECT: 'EXPERIMENT:LBL_PROJECT',
    LBL_VIEW_FIELDS: 'EXPERIMENT:LBL_VIEW_FIELDS',
    LBL_EXPERIMENT_ID: 'EXPERIMENT:LBL_EXPERIMENT_ID',
    LBL_NO_OF_ENTRIES: 'EXPERIMENT:LBL_NO_OF_ENTRIES',
    LBL_FIELD_DESIGN: 'EXPERIMENT:LBL_FIELD_DESIGN',
    LBL_SEASON: 'EXPERIMENT:LBL_SEASON',
    LBL_ENTRIES: 'EXPERIMENT:LBL_ENTRIES',
    LBL_PLOTS: 'EXPERIMENT:LBL_PLOTS',
    LBL_REPLICATION: 'EXPERIMENT:LBL_REPLICATION',
    LBL_RANDOMISATION: 'EXPERIMENT:LBL_RANDOMISATION',
    LBL_LOCATION: 'EXPERIMENT:LBL_LOCATION',
    LBL_FIELD: 'EXPERIMENT:LBL_FIELD',
    LBL_NO_OF_TRAITS: 'EXPERIMENT:LBL_NO_OF_TRAITS',
    LBL_VIEW: 'EXPERIMENT:LBL_VIEW',
    LBL_VIEW_ALL_FIELDS: 'EXPERIMENT:LBL_VIEW_ALL_FIELDS',
  },
};

export {LOCALES};
